local button = require "main.scripts.button"

local function create_blue_button(node, spite, callback)
	return button.create(node, spite, spite, callback)
end

function init(self)
	msg.post(".", "acquire_input_focus")
	self.gun = create_blue_button(gui.get_node("gun"), hash("char_gun"), function()
		print("gun")
	end)
end

function on_input(self, action_id, action)
	if self.gun.on_input(action_id, action) then
		return true
	end
end